---

- name: Destroy Palworld Dedicated Server container
  hosts: palworld
  become: true
  tasks:
    - name: Destroy all containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: true
        keep_volumes: false
      loop:
        - palworld-dedicated-server
        - palworld-exporter
