---

- name: Install Docker on all hosts
  hosts: all
  become: true
  tasks:
    - name: Fetch Debian package architecture name
      ansible.builtin.command: dpkg --print-architecture
      register: _dpkg_architecture
      changed_when: false
    - name: Set Debian package architecture name
      ansible.builtin.set_fact:
        dpkg_architecture: "{{ _dpkg_architecture.stdout }}"
    - name: Install Docker APT GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        owner: root
        group: root
        mode: "0644"
    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: >-
          deb [arch={{ dpkg_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/{{ ansible_distribution | lower }}
          {{ ansible_distribution_release }}
          stable
    - name: Install Docker, Docker Compose V2, and Python bindings
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - python3-docker
    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      when: not (palworld_dedicated_server_molecule_docker | default(False))
