---

- name: Check that Palworld Dedicated Server has been disabled
  hosts: palworld
  become: true
  tasks:
    - name: Check that data directory still exists
      ansible.builtin.stat:
        path: /opt/palworld-dedicated-server/data
      register: data_dir
      failed_when: not (data_dir.stat.isdir | default(False))
    - name: Check that the compose file still exists
      ansible.builtin.stat:
        path: /opt/palworld-dedicated-server/docker-compose.yml
      register: dockercompose_file
      failed_when: not (dockercompose_file.stat.isreg | default(False))
    - name: Check service status (if not running in Molecule using Docker)
      when: not (palworld_dedicated_server_molecule_docker | default(False))
      block:
        - name: Get container info
          community.docker.docker_container_info:
            name: palworld-dedicated-server
          register: result
        - name: Check that the container does not exist
          ansible.builtin.assert:
            that:
              - not result.exists
            success_msg: Container does not exist
            fail_msg: Container exists
            quiet: true
