---

- name: Check that Palworld Dedicated Server is running
  hosts: palworld
  become: true
  tasks:
    - name: Get service user metadata
      ansible.builtin.getent:
        database: passwd
        key: palworld
    - name: Check that the service user has the correct UID
      ansible.builtin.assert:
        that:
          - (getent_passwd['palworld'][1] | int) == palworld_dedicated_server_user_uid
        success_msg: "Service user has the correct UID {{ palworld_dedicated_server_user_uid }}"
        fail_msg: >-
          Service user has the incorrect UID {{ getent_passwd['palworld'][1] }},
          expected {{ palworld_dedicated_server_user_uid }}
        quiet: true
    - name: Check that the service user has the correct GID
      ansible.builtin.assert:
        that:
          - (getent_passwd['palworld'][2] | int) == palworld_dedicated_server_user_gid
        success_msg: "Service user has the correct GID {{ palworld_dedicated_server_user_uid }}"
        fail_msg: >-
          Service user has the incorrect GID {{ getent_passwd['palworld'][2] }},
          expected {{ palworld_dedicated_server_user_gid }}
        quiet: true
    - name: Check that data directory exists
      ansible.builtin.stat:
        path: /opt/palworld/data
      register: data_dir
      failed_when: not (data_dir.stat.isdir | default(False))
    - name: Check that the compose file exists
      ansible.builtin.stat:
        path: /opt/palworld/docker-compose.yml
      register: dockercompose_file
      failed_when: not (dockercompose_file.stat.isreg | default(False))
    - name: Check service status (if not running in Molecule using Docker)
      when: not (palworld_dedicated_server_molecule_docker | default(False))
      block:
        - name: Get container info
          community.docker.docker_container_info:
            name: palworld-dedicated-server
          register: result
        - name: Check that the container is running
          ansible.builtin.assert:
            that:
              - result.container.State.Running
            success_msg: Container is running
            fail_msg: Container is not running
            quiet: true
        - name: Check that the RCON port is open (if enabled)
          ansible.builtin.wait_for:
            port: "{{ palworld_dedicated_server_rcon_port }}"
            timeout: 30
          when: palworld_dedicated_server_rcon_enable | default(False)
