name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
      - name: Run Molecule tests
        uses: gofrolist/molecule-action@v2
        with:
          molecule_args: --scenario-name docker
