name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install Ansible and Molecule
        run: python -m pip install -r requirements.txt
      - name: Setup Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.24.5"
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
      - name: Run Molecule tests
        run: molecule test --scenario-name localhost
